FORMAT: 1A

# Repo Service

This is a RESTful API for repository management


## Group API Root

This resource offers the initial API capabilities in
the form of the links in the JSON body.

## API Root Collection [/]
### List All Resources [GET]
+ Response 200 (application/json)

        [
            { "href": "http://localhost:3001/users" },
            { "href": "http://localhost:3001/repos" }
        ]

## Group Users
## Users Collection [/users]
### List All Users [GET]
### Create a New User [POST]


## Group User
## User [/users/{user_id}]
### View User [GET]


## Group Repos
## Repos Collection [/repos]
### List All Repos [GET]
### Create a New Repo [POST]


## Group Repo
## Repo [/repos/{repo_id}]
### View Repo [GET]
### Delete Repo [DELETE]
